timeout: 5
serial: no
term_background: 000000

/Raytolfas OS D1
    protocol: linux
    path: boot():/boot/vmlinuz
    module_path: boot():/boot/initramfs.cpio.gz
    cmdline: console=tty0 rdinit=/init loglevel=0 quiet splash systemd.show_status=0 rd.udev.log_level=0 vt.global_cursor_default=0 fbcon=nodefer selinux=0 ahci.mobile_lpm_policy=0

/Raytolfas OS D1 (Safe Graphics)
    protocol: linux
    path: boot():/boot/vmlinuz
    module_path: boot():/boot/initramfs.cpio.gz
    cmdline: console=tty0 rdinit=/init loglevel=0 nomodeset quiet splash systemd.show_status=0 rd.udev.log_level=0 vt.global_cursor_default=0 fbcon=nodefer selinux=0 ahci.mobile_lpm_policy=0
