---
efiSystemPartition: "/boot/efi"
enableLuksAutomatedPartitioning: false
userSwapChoices:
    - none
    - file
initialSwapChoice: none
drawNestedPartitions: true
defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4","btrfs","xfs"]
partitionLayout:
    - name: "raytolfas_root"
      filesystem: unknown
      mountPoint: "/"
      size: 100%
