modules-search: [ local, /usr/lib/x86_64-linux-gnu/calamares/modules, /usr/share/calamares/modules ]

instances:
- id:       rootfs
  module:   unpackfs
  config:   unpackfs.conf
- id:       cleanup
  module:   shellprocess
  config:   shellprocess-cleanup.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs@rootfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - grubcfg
  - bootloader
  - shellprocess@cleanup
  - umount
- show:
  - finished

branding: raytolfas

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
expert-mode: false
