dontChroot: false
timeout: 30
script:
    - "rm -f /home/*/Desktop/calamares.desktop"
    - "rm -f /etc/skel/Desktop/calamares.desktop"
    - "rm -f /usr/share/applications/calamares.desktop"
    - "rm -f /usr/local/bin/raytolfas-install"
